language: rust
cache: cargo
dist: xenial
os: 
  - linux
  - osx

# Run builds for all the supported trains
rust:
  - nightly
  - beta
  - stable
  - 1.31.0

# It may not be our fault if a Rust nightly breaks, so we tolerate it
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

# The main build
before_script:
  - rustup component add clippy
script:
  - cargo check
  - cargo clippy
  - cargo test --tests
  - cargo test --features raw
  - cargo test --release -- --ignored --nocapture --test-threads=1
  - cargo test --release --features raw -- --ignored --nocapture --test-threads=1
